config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'home#index'

resources :task_lists, only: [:index, :show, :new, :create] do
   resources :tasks, only: [:index, :show, :new, :create]
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :task_list
  validates :title, presence: true
end

app/models/task_list.rb
class TaskList < ApplicationRecord
  has_many :tasks
  belongs_to :user
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :task_lists
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @task = TaskList.all
  end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController

  def index
    @lists = TaskList.all
  end

  def show
    @task_list = TaskList.find(params[:id])
  end

  def new
    @list = TaskList.new
  end

  def create
    @tasklist = TaskList.new task_list_params
    @tasklist.user = current_user
    if @tasklist.save
      redirect_to root_path
    else
      flash[:error] = 'Campo título e obrigatório!'
      render :new
    end
  end

  private

  def task_list_params
   params.require(:task_list).permit(:title)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @task = Task.all
  end
  def new
    @task = Task.new
    @task_list = TaskList.find(params[:task_list_id])
  end
  def create
    tasks_params = params.require(:task).permit(:title, :description)
    @task_list = TaskList.find(params[:task_list_id])
    @task_list.tasks.build(tasks_params)

    if @task_list.save
      redirect_to  task_list_path(@task_list)
    else
      flash[:error] = 'Campo Título é obrigatório'
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1> Lista de Tarefas Pública </h1>
<p> Bem-vindo a maior lista de tarefas online </p>

<% if user_signed_in? %>

  <% @task.each do |list| %>
    <ul>
    <li><%= link_to list.title, task_list_path(list.id) %></li>
    </ul>
  <% end %>

  </div>
  <div>
    <%= link_to 'Criar nova lista', new_task_list_path %>
  </div>

  <div>
    <%= link_to 'Sair',  destroy_user_session_path, method: :delete %>
  </div>

<% else %>
  <%= link_to 'log in', new_user_session_path %>
  <%= link_to 'Sign up', new_user_registration_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p><%=flash[:notice]%></p>
    <p><%=flash[:alert]%></p>
    <%= yield %>
  </body>
</html>

app/views/task_lists/index.html.erb
<h1> Tarefas </h1>
<% @lists.each do |list| %>
    <% if list.public_list %>
        <h3><%= list.title %></h3>
      <% @list.tasks.each do |task| %>
        <h4><%= link_to task.title %></h4>
        <ul>
            <li><%= task.description %></li>
        </ul>
      <% end %>
    <% end %>
<% end %>

<% @lists.each do |list| %>
  <%= link_to list.title, task_list_path(list.id) %>
<% end %>

app/views/task_lists/new.html.erb
<%= form_for(@list) do |list| %>
  <div>
   <%= list.label :title, 'Título' %>
   <%= list.text_field :title %>
  </div>
  <div>
    <%= list.label :public_list, 'Lista Pública' %>
    <%= list.select(:public_list, options_for_select([['Sim', true], ['Não', false]])) %>
  </div>
  <div>
    <%= list.submit 'Enviar' %>
  </div>
<% end %>

app/views/task_lists/show.html.erb
<h1> Lista de Tarefas Pública </h1>
<% @task_list.tasks.each do |task| %>
  <h3><%= task.title %></h3>
  <h4><%= task.description %></h4>
<% end %>

<div>
  <%= link_to 'Ver todas as listas',root_path %>
</div>

<div>
  <%= link_to 'Home', root_path %>
</div>

<div>
<%= link_to 'Sair',  destroy_user_session_path, method: :delete %>
</div>

<% if @task_list.user == current_user %>
  <%= link_to 'Adicionar nova tarefa', new_task_list_task_path(@task_list) %>
<% end %>

app/views/tasks/new.html.erb
<%= form_for([@task_list, @task]) do |f| %>
  <div>
  <%= f.label :title, 'Título' %>
  <%= f.text_field :title %>
  </div>
  <div>
  <%= f.label :description, 'Comentário' %>
  <%= f.text_field :description %>
  <div>
  </div>
  <%= f.submit 'Salvar' %>
<% end %>

app/views/tasks/show.html.erb
<%= link_to 'Adicionar nova tarefa', banana_path %>